language: objective-c
xcode_workspace: Provenance.xcworkspace # path to your xcodeproj folder
xcode_scheme: Provenance-Release

language: objective-c
osx_image: xcode9.3

cache:
  directories:
  - Carthage
  - PVSupport/Carthage

# branches:
#   only:
#     - develop
#     - master
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
  - gem install xcpretty -N
  - brew update
  - brew outdated swiftlint || brew upgrade swiftlint
  - brew outdated carthage || brew upgrade carthage
  - cd PVSupport
  - carthage bootstrap --verbose --no-use-binaries --platform iOS --cache-builds
  - cd ..
after_success:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
script:
  - set -o pipefail
  - xcodebuild -workspace Provenance.xcworkspace -scheme Provenance-Release -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO | xcpretty -c
  - swiftlint
